In [10]:
import pandas as pd
import os
import sys

# Ensure the correct directory paths
init_dir = os.getcwd()
parent_dir = os.path.dirname(init_dir)
mlc_dir = os.path.join(init_dir, "mlc")
sys.path.append(mlc_dir)
# Install the cashflow module if not found
try:
	import cashflow
except ModuleNotFoundError:
	print("Module 'cashflow' not found. Please ensure it exists in the directory:", mlc_dir)

In [11]:
df_consumers = pd.read_parquet(parent_dir+"/cashflow-data/consumer_data.parquet")
df_transactions = pd.read_parquet(parent_dir+"/cashflow-data/transactions.parquet")

In [12]:
merged_df = df_transactions.merge(df_consumers, on = "masked_consumer_id")
filtered_df = merged_df[merged_df["posted_date"]< merged_df["evaluation_date"]]

In [13]:
filtered_df["loan_type"] = filtered_df["masked_consumer_id"].str[2]
filtered_df["loan_type"] = filtered_df["loan_type"].astype(int)

C:\Users\18585\AppData\Local\Temp\ipykernel_21732\4155308201.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["loan_type"] = filtered_df["masked_consumer_id"].str[2]
C:\Users\18585\AppData\Local\Temp\ipykernel_21732\4155308201.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["loan_type"] = filtered_df["loan_type"].astype(int)

In [14]:
filtered_df

,masked_consumer_id,posted_date,amount,category,masked_transaction_id,evaluation_date,FPF_TARGET,total_balance,loan_type
0,C02103629,2022-08-12,-21.00,27.0,C02T02715977,2022-11-16,1.0,109.53,2
1,C02103629,2022-08-09,-8.60,22.0,C02T02715978,2022-11-16,1.0,109.53,2
2,C02103629,2022-08-07,-30.05,16.0,C02T02715979,2022-11-16,1.0,109.53,2
3,C02103629,2022-09-29,-0.46,0.0,C02T02715980,2022-11-16,1.0,109.53,2
4,C02103629,2022-07-21,-50.00,12.0,C02T02715981,2022-11-16,1.0,109.53,2
...,...,...,...,...,...,...,...,...,...
17737465,C04100783,2022-03-29,-11.20,14.0,C04T01071462,2022-03-31,0.0,1104.86,4
17737466,C04100783,2022-03-29,-1.00,1.0,C04T01071463,2022-03-31,0.0,1104.86,4
17737467,C04100783,2022-03-30,-2.00,1.0,C04T01071464,2022-03-31,0.0,1104.86,4
17737468,C04100783,2022-03-30,-15.00,17.0,C04T01071465,2022-03-31,0.0,1104.86,4
17737469,C04100783,2022-03-30,-7.96,14.0,C04T01071466,2022-03-31,0.0,1104.86,4

dataframes_by_loans is a dictionary. Keys of which correspond to loan type, mapping to the merged dataframe that contains transactions and evaluation data.

In [51]:
dataframes_by_loans = {lt: pd.DataFrame() for lt in filtered_df.loan_type.unique()}
for key in dataframes_by_loans:
    dataframes_by_loans[key] = filtered_df[:][filtered_df.loan_type == key]

In [55]:
dataframes_by_loans[1]

,masked_consumer_id,posted_date,amount,category,masked_transaction_id,evaluation_date,FPF_TARGET,total_balance,loan_type
4436977,C01103696,2022-05-02,400.00,1.0,C01T04156275,2022-09-15,0.0,2240.75,1
4436978,C01103696,2022-06-09,38.00,1.0,C01T04156276,2022-09-15,0.0,2240.75,1
4436979,C01103696,2022-08-13,4.00,6.0,C01T04156277,2022-09-15,0.0,2240.75,1
4436980,C01103696,2022-09-13,0.17,7.0,C01T04156278,2022-09-15,0.0,2240.75,1
4436981,C01103696,2022-02-24,2095.00,1.0,C01T04156279,2022-09-15,0.0,2240.75,1
...,...,...,...,...,...,...,...,...,...
16658989,C01102465,2021-08-17,-70.00,14.0,C01T02770794,2022-04-05,0.0,27449.88,1
16658990,C01102465,2021-04-12,-1000.00,19.0,C01T02770795,2022-04-05,0.0,27449.88,1
16658991,C01102465,2022-03-14,-160.05,22.0,C01T02770796,2022-04-05,0.0,27449.88,1
16658992,C01102465,2021-09-23,-0.02,1.0,C01T02770797,2022-04-05,0.0,27449.88,1
16658993,C01102465,2021-12-30,-2.02,15.0,C01T02770798,2022-04-05,0.0,27449.88,1

In [3]:
df_consumers = pd.read_parquet(init_dir+"/mlc-cashflow/mlc/test_data/consumer_data.parquet")
df_transactions = pd.read_parquet(init_dir+"/mlc-cashflow/mlc/test_data/transactions.parquet")