# Data Splitting

In [1]:
import pandas as pd
import os

In [2]:
consumer_df = pd.read_parquet("/Users/jasonc/Desktop/DSC_291/cashflow/consumer_data.parquet")

In [3]:
transaction_df = pd.read_parquet("/Users/jasonc/Desktop/DSC_291/cashflow/transactions.parquet")

In [4]:
consumer_df.head()

  evaluation_date  FPF_TARGET  total_balance masked_consumer_id
0      2021-08-26         0.0        1380.84          C01100001
1      2022-08-02         0.0       20163.90          C01100002
2      2021-03-04         0.0        3986.25          C01100003
3      2022-11-19         0.0        5956.03          C01100004
4      2021-11-21         0.0       29421.10          C01100005

In [5]:
transaction_df.head()

        masked_consumer_id posted_date  amount  category masked_transaction_id
2715977          C02103629  2022-08-12  -21.00      27.0          C02T02715977
2715978          C02103629  2022-08-09   -8.60      22.0          C02T02715978
2715979          C02103629  2022-08-07  -30.05      16.0          C02T02715979
2715980          C02103629  2022-09-29   -0.46       0.0          C02T02715980
2715981          C02103629  2022-07-21  -50.00      12.0          C02T02715981

In [6]:
# Get a number of unique consumers first:
unique_consumers = transaction_df['masked_consumer_id'].unique()
print(f"Total unique consumers: {len(unique_consumers)}")

Total unique consumers: 16000

In [7]:
# Dictionary: key = consumer ID, value = their transactions (as DataFrame)
consumer_transactions = {
    consumer_id: group.reset_index(drop=True)
    for consumer_id, group in transaction_df.groupby("masked_consumer_id")
}

In [8]:
# Save separated transactions:
output_dir = "/Users/jasonc/Desktop/DSC_291/split_transactions"
os.makedirs(output_dir, exist_ok=True)

for consumer_id, df in consumer_transactions.items():
    df.to_parquet(f"{output_dir}/{consumer_id}.parquet", index=False)

In [9]:
# Example of one splitted transction:
consumer_1 = pd.read_parquet("/Users/jasonc/Desktop/DSC_291/split_transactions/C01100001.parquet")

In [10]:
consumer_1

     masked_consumer_id posted_date   amount  category masked_transaction_id
0             C01100001  2021-06-29   926.89       4.0                C01T00
1             C01100001  2020-11-16   300.00       0.0                C01T01
2             C01100001  2020-11-25   500.00       0.0                C01T02
3             C01100001  2020-09-03  1000.00       0.0                C01T03
4             C01100001  2020-11-09   200.00       0.0                C01T04
...                 ...         ...      ...       ...                   ...
2653          C01100001  2021-03-08 -7000.00       1.0             C01T02653
2654          C01100001  2020-09-30   -17.12      19.0             C01T02654
2655          C01100001  2020-11-23    -3.99      20.0             C01T02655
2656          C01100001  2021-05-17   -53.00      27.0             C01T02656
2657          C01100001  2020-09-11    -8.49      22.0             C01T02657

[2658 rows x 5 columns]